<?php


echo '<div class="igItemAttr" style="display: none;">';

$cart = Mage::getModel('checkout/cart')->getQuote();
$helper = Mage::helper('stores');
foreach ($cart->getAllVisibleItems() as $item) {
    echo '<div class="igItemDetails '.$item->getName().'">';
    $details = $helper->getItemDetails($item);

    /* figure this item type problem out, okay?
		$options = $item->getOptionByCode('simple_product')->getProduct()->getTypeInstance(true)->getOrderOptions($item->getProduct());
		  if ($options){
			if(isset($options['options'])){
				echo '<span class="igItemOptions"><dl class="igOptionsList">';
				$optionArray = $options['options'];
				foreach ($optionArray as $optionDetails) {
					echo '<dt>' . $optionDetails['label'] . '</dt>';
					echo '<dd>' . $optionDetails['value'] . '</dd>';
				}
				echo '</dl></span>';
			}
		  } */

    echo '<span class="igID">'.$details['productId'].'</span>';
    echo '<span class="igName">'.$details['description'].'</span>';
    echo '<span class="igSku">'.$details['sku'].'</span>';
    echo '<span class="igQty">'.$details['quantity'].'</span>';
    echo '<span class="igPrice">'.$details['unitPrice'].'</span>';
    echo '<span class="igUrl">'.$details['itemURL'].'</span>';
    echo '<span class="igImage">'. $details['imageURL'].'</span>';
    echo '<span class="igDescription">'.$details['itemDescriptionLong'].'</span>';
    echo '<span class="igShortDescription">'.$item->getProduct()->getShortDescription().'</span>';
    echo '<span class="MageWeight">'.$details['weight'].'</span>';

    // echo "<div class='ig_itemAttributes' style='display:none;'>";
    echo "<span class='ig_itemProductId'>".$details['productId']."</span>";
    echo "<span class='ig_itemSku'>".$details['sku']."</span>";
    echo "<span class='ig_itemPrice'>".$details['unitPrice']."</span>";
    echo "<span class='ig_itemWeight'>".$details['weight']."</span>";
    echo "<span class='ig_itemLength'>".$details['length']."</span>";
    echo "<span class='ig_itemWidth'>".$details['width']."</span>";
    echo "<span class='ig_itemHeight'>".$details['height']."</span>";
    //echo "</div>";

    echo '</div><!-- end igItemDetails-->';
}

echo '</div><!--end igItemAttr-->';
