<?php

	//build our URL to be able to check for cart page
	$url = 'http://' . $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI'];

	//label the area of DOM
	echo '<!--Added for iGlobal-->';

	//set include for welcome mat
	if (Mage::getStoreConfig('iglobal_integration/igmat/welcome_mat_active')){ //welcome mat is on
		
			if (Mage::getStoreConfig('iglobal_integration/igmat/welcome_mat_script')){ //custom welcome mat js has been uploaded
			
				//include custom welcome mat
				echo '<script type="text/javascript" src="' . Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) . 'iGlobal/'.Mage::getStoreConfig('iglobal_integration/igmat/welcome_mat_script').'"></script>'; // use this call in production
						
			} else { //welcome mat is on, but no custom file has been uploaded
				
				//include default welcome mat
				echo '<script type="text/javascript" src="' . Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) . 'iGlobal/ig_welcome_mat_default.js"></script>'; //production call

			}
			
			
			if (Mage::getStoreConfig('iglobal_integration/igmat/welcome_mat_css')){ //custom welcome mat css has been uploaded
			
				//add css for welcome mat too
				echo '<link rel="stylesheet" type="text/css" href="' . Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) . 'iGlobal/' . Mage::getStoreConfig('iglobal_integration/igmat/welcome_mat_css') . '">' ; // use this call in production
			
			} else { //welcome mat is on, but no custom file has been uploaded
				
				//include default welcome mat css
				echo '<link rel="stylesheet" type="text/css" href="' . Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) . 'iGlobal/ig_welcome_mat_default.css">'; //production call

			}
			
	} else { 
		//welcome mat is off
		echo '<span id="welcome_mat_deactivated" display="none"></span>';
	}

	//set includes for ICE and main
	if (Mage::getStoreConfig('iglobal_integration/apireqs/ice_toggle') && Mage::getStoreConfig('iglobal_integration/apireqs/use_ice')) { //&& ((false !== strpos($url,'cart')) || (false !== strpos($url,'checkout')))
		
		//include main js
		 echo '<script type="text/javascript" src="https://checkout.iglobalstores.com/js/igc.cs.main.js"></script>'; 
		
		if (Mage::getStoreConfig('iglobal_integration/apireqs/ice')){
			//include custom ICE
			echo '<script type="text/javascript" src="'.Mage::getStoreConfig('iglobal_integration/apireqs/ice').'"></script>';
		} else {
			//include default ICE
			echo '<script type="text/javascript" src="' . Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) . 'iGlobal/igc.cs.magento_default_ice.js"></script>'; 
		}
	}
	
	echo '<!--End of iGlobal-->';
?>