<NotepadPlus>
    <Session activeView="0">
        <mainView activeIndex="14">
            <File firstVisibleLine="63" xOffset="0" scrollWidth="1432" startPos="1816" endPos="1816" selMode="0" lang="PHP" encoding="-1" filename="C:\magentostack6\apps\magento\htdocs\app\design\frontend\base\default\template\iglobal\stores\cart.phtml" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="956" startPos="0" endPos="0" selMode="0" lang="PHP" encoding="-1" filename="C:\Users\mattf_000\Desktop\cart2.phtml" />
            <File firstVisibleLine="0" xOffset="6" scrollWidth="981" startPos="302" endPos="407" selMode="0" lang="PHP" encoding="-1" filename="C:\Users\mattf_000\Desktop\cart7.phtml" />
            <File firstVisibleLine="0" xOffset="55" scrollWidth="956" startPos="302" endPos="302" selMode="0" lang="PHP" encoding="-1" filename="C:\Users\mattf_000\Desktop\cart4.phtml" />
            <File firstVisibleLine="39" xOffset="0" scrollWidth="1482" startPos="2046" endPos="2046" selMode="0" lang="Javascript" encoding="-1" filename="C:\magentostack6\apps\magento\htdocs\js\iGlobal\igc.cs.magento_default_ice.js" />
            <File firstVisibleLine="21" xOffset="0" scrollWidth="25095" startPos="4516" endPos="4516" selMode="0" lang="Javascript" encoding="-1" filename="C:\magentostack6\apps\magento\htdocs\js\iGlobal\ig_welcome_mat_default.js" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="270" startPos="119" endPos="119" selMode="0" lang="XML" encoding="-1" filename="C:\magentostack6\apps\magento\htdocs\app\code\community\Iglobal\Stores\etc\config.xml" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="180" startPos="0" endPos="0" selMode="0" lang="PHP" encoding="-1" filename="C:\Users\mattf_000\Downloads\extension\extension\app\design\frontend\base\default\template\zxyxz_store\cart.phtml" />
            <File firstVisibleLine="6" xOffset="0" scrollWidth="556" startPos="1322" endPos="1262" selMode="0" lang="PHP" encoding="-1" filename="C:\Users\mattf_000\Downloads\extension\extension\app\code\community\Zxyxz\Store\Block\Cart.php" />
            <File firstVisibleLine="112" xOffset="0" scrollWidth="209551" startPos="97767" endPos="97767" selMode="0" lang="Javascript" encoding="-1" filename="C:\nginx\html\igc.cs.shoolu.js" />
            <File firstVisibleLine="41" xOffset="0" scrollWidth="1631" startPos="3491" endPos="1794" selMode="0" lang="Javascript" encoding="-1" filename="C:\nginx\html\igc.cs.gourmetnew.js" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="979" startPos="0" endPos="0" selMode="0" lang="PHP" encoding="-1" filename="C:\magentostack6\apps\magento\htdocs\app\code\community\Iglobal\Stores\sql\iglobal_stores_setup\mysql4-install-0.1.0.php" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="253" startPos="0" endPos="0" selMode="0" lang="PHP" encoding="-1" filename="C:\magentostack6\apps\magento\htdocs\app\code\community\Iglobal\Stores\sql\iglobal_stores_setup\mysql4-upgrade-0.1.0-0.1.1.php" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="724" startPos="0" endPos="0" selMode="0" lang="PHP" encoding="-1" filename="C:\magentostack6\apps\magento\htdocs\app\code\community\Iglobal\Stores\sql\iglobal_stores_setup\mysql4-upgrade-0.1.1-0.1.2.php" />
            <File firstVisibleLine="0" xOffset="0" scrollWidth="1225" startPos="0" endPos="0" selMode="0" lang="PHP" encoding="-1" filename="C:\magentostack6\apps\magento\htdocs\app\code\community\Iglobal\Stores\controllers\SuccessController.php" />
        </mainView>
        <subView activeIndex="0" />
    </Session>
</NotepadPlus>
